---
- name: Pull Host Repo
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Pull Host Git Repo
      # noqa: latest
      ansible.builtin.git:
        repo: "{{ _repo }}"
        dest: "{{ _p_root }}"
      register: exec_git_host_git_repo
      tags: always

    - name: DEBUG
      ansible.builtin.debug:
        msg:
          exec_git_host_git_repo: "{{ exec_git_host_git_repo | default('NA')}}"
      tags: always